version: '3.0'
services:
  Ayush10:
    container_name: 'Ayush10'
    build:
      context: './'
    image: 'tridevai/tridev'
    ports:
      - '${tridev_PORT:-1337}:${tridev_PORT:-1337}'
    environment:
      tridev_PORT: ${tridev_PORT:-1337}
    stdin_open: true
    tty: true
    command: 'npm run dev:server && npm run dev:app'
    volumes:
      - './:/app'
      - '/app/node_modules'
